server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
spring:
  application:
    name: cloud-order-service
#设置feign客户端超时时间
feign:
  client:
    config:
      #default代表所有服务
      default:
        #feign客户端建立连接超时时间
        connectTimeout: 10000
        #feign客户端建立连接后读取资源超时时间
        readTimeout: 20000
        #日志级别
        logger-level: full
      #而service-test表示当调用service-test这个服务时，用下面的配置
      service-test:
        connect-timeout: 10000
        read-timeout: 20000
logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.xc.springcloud.service.PaymentService: debug
